nome = input("Qual é o seu nome? ")
idade = input("Qual é a sua idade? ")
signo = input("Qual é o seu signo? ")
print(nome, idade, signo)
print('Oi, ', nome, '! É um prazer te conhecer')

dia = input("Qual o dia do seu nascimento? ")
mes = input("Qual o mês do seu aniversário? ")
ano = input("Em que ano você nasceu? ")
print('Você nasceu no dia', dia, ' de ', mes, ' de ', ano, '. Correto?')
